# See the documentation for more information:
# https://packit.dev/docs/configuration/
specfile_path: httpie.spec
actions:
  # get the current Fedora Rawhide specfile:
  post-upstream-clone: "wget https://src.fedoraproject.org/rpms/httpie/raw/rawhide/f/httpie.spec -O httpie.spec"
  # Use this when the latest spec is not up-to-date.
  # post-upstream-clone: "cp docs/packaging/linux-fedora/httpie.spec.txt httpie.spec"
jobs:
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches:
    - rawhide
