complete	-c	http	-s	--json	-l	-j	-d	'(default) Serialize data items from the command line as a JSON object.'
complete	-c	http	-s	--form	-l	-f	-d	'Serialize data items from the command line as form field data.'
complete	-c	http	-l	--multipart	-d	'Similar to --form, but always sends a multipart/form-data request (i.e., even without files).'
complete	-c	http	-l	--boundary	-d	'Specify a custom boundary string for multipart/form-data requests. Only has effect only together with --form.'
complete	-c	http	-l	--raw	-d	'Pass raw request data without extra processing.'
complete	-c	http	-s	--compress	-l	-x	-d	'Compress the content with Deflate algorithm.'
complete	-c	http	-l	--pretty	-xa	"all colors format none"	-d	'Control the processing of console outputs.'
complete	-c	http	-s	--style	-l	-s	-d	'Output coloring style (default is "auto").'
complete	-c	http	-l	--unsorted	-d	'Disables all sorting while formatting output.'
complete	-c	http	-l	--sorted	-d	'Re-enables all sorting options while formatting output.'
complete	-c	http	-l	--response-charset	-d	'Override the response encoding for terminal display purposes.'
complete	-c	http	-l	--response-mime	-d	'Override the response mime type for coloring and formatting for the terminal.'
complete	-c	http	-l	--format-options	-d	'Controls output formatting.'
complete	-c	http	-s	--print	-l	-p	-d	'Options to specify what the console output should contain.'
complete	-c	http	-s	--headers	-l	-h	-d	'Print only the response headers.'
complete	-c	http	-s	--meta	-l	-m	-d	'Print only the response metadata.'
complete	-c	http	-s	--body	-l	-b	-d	'Print only the response body.'
complete	-c	http	-s	--verbose	-l	-v	-d	'Make output more verbose.'
complete	-c	http	-l	--all	-d	'Show any intermediary requests/responses.'
complete	-c	http	-s	--stream	-l	-S	-d	'Always stream the response body by line, i.e., behave like `tail -f`.'
complete	-c	http	-s	--output	-l	-o	-d	'Save output to FILE instead of stdout.'
complete	-c	http	-s	--download	-l	-d	-d	'Download the body to a file instead of printing it to stdout.'
complete	-c	http	-s	--continue	-l	-c	-d	'Resume an interrupted download (--output needs to be specified).'
complete	-c	http	-s	--quiet	-l	-q	-d	'Do not print to stdout or stderr, except for errors and warnings when provided once.'
complete	-c	http	-l	--session	-d	'Create, or reuse and update a session.'
complete	-c	http	-l	--session-read-only	-d	'Create or read a session without updating it'
complete	-c	http	-s	--auth	-l	-a	-d	'Credentials for the selected (-A) authentication method.'
complete	-c	http	-s	--auth-type	-l	-A	-d	'The authentication mechanism to be used.'
complete	-c	http	-l	--ignore-netrc	-d	'Ignore credentials from .netrc.'
complete	-c	http	-l	--offline	-d	'Build the request and print it but don’t actually send it.'
complete	-c	http	-l	--proxy	-d	'String mapping of protocol to the URL of the proxy.'
complete	-c	http	-s	--follow	-l	-F	-d	'Follow 30x Location redirects.'
complete	-c	http	-l	--max-redirects	-d	'The maximum number of redirects that should be followed (with --follow).'
complete	-c	http	-l	--max-headers	-d	'The maximum number of response headers to be read before giving up (default 0, i.e., no limit).'
complete	-c	http	-l	--timeout	-d	'The connection timeout of the request in seconds.'
complete	-c	http	-l	--check-status	-d	'Exit with an error status code if the server replies with an error.'
complete	-c	http	-l	--path-as-is	-d	'Bypass dot segment (/../ or /./) URL squashing.'
complete	-c	http	-l	--chunked	-d	'Enable streaming via chunked transfer encoding. The Transfer-Encoding header is set to chunked.'
complete	-c	http	-l	--verify	-d	'If "no", skip SSL verification. If a file path, use it as a CA bundle.'
complete	-c	http	-l	--ssl	-xa	"ssl2.3 tls1 tls1.1 tls1.2"	-d	'The desired protocol version to used.'
complete	-c	http	-l	--ciphers	-d	'A string in the OpenSSL cipher list format.'
complete	-c	http	-l	--cert	-d	'Specifys a local cert to use as client side SSL certificate.'
complete	-c	http	-l	--cert-key	-d	'The private key to use with SSL. Only needed if --cert is given.'
complete	-c	http	-l	--cert-key-pass	-d	'The passphrase to be used to with the given private key.'
complete	-c	http	-s	--ignore-stdin	-l	-I	-d	'Do not attempt to read stdin'
complete	-c	http	-l	--help	-d	'Show this help message and exit.'
complete	-c	http	-l	--manual	-d	'Show the full manual.'
complete	-c	http	-l	--version	-d	'Show version and exit.'
complete	-c	http	-l	--traceback	-d	'Prints the exception traceback should one occur.'
complete	-c	http	-l	--default-scheme	-d	'The default scheme to use if not specified in the URL.'
complete	-c	http	-l	--debug	-d	'Print useful diagnostic information for bug reports.'
