name: Check installation instructions

on:
  pull_request:
    paths:
      - docs/generate-install-instructions.py

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: make install
      - run: make doc-install-inst
