name: Check documentations

on:
  pull_request:
    paths:
      - "*.md"
      - "**/*.md"

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install the linter
        run: gem install mdl
      - name: Check files
        run: make doc-check
