name: Update documentation

on:
  push:
    branches:
      - master
    paths:
      - docs/README.md
  release:
    types:
      - published

jobs:
  trigger-doc-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger new documentation build
        run: curl -X POST ${{ secrets.DOCS_UPDATE_VERCEL_HOOK }}
